# Generated by Django 4.1.4 on 2022-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ushort", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlshort", name="visitor", field=models.IntegerField(default=0),
        ),
    ]
